FROM node:20

WORKDIR /app

# Copiar package.json e instalar dependências
COPY package*.json ./
RUN npm install

# Copiar código
COPY . .

# Expõe a porta padrão do Angular
EXPOSE 4200

# Rodar em modo dev (ng serve)
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]
