server {
  listen 80;

  location / {
    # Define a pasta raiz onde estão os arquivos da sua aplicação Angular
    root /usr/share/nginx/html;
    
    # Define o arquivo padrão a ser servido
    index index.html index.htm;

    # Redireciona todas as requisições para o index.html
    try_files $uri $uri/ /index.html;
  }
}