services:
  app:
    build: .  
    ports:
      - "5001:5000"
    env_file:  
      - .env   
    depends_on:
      - ollama 

  ollama:
    image: ollama/ollama 
    volumes:
      - ollama_data:/root/.ollama 
    ports:
      - "11434:11434" 

volumes:
  ollama_data: 