services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: angular-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
