FROM python:3.11-bookworm

ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
ENV FLASK_APP=app.py

# Instalar dependências do sistema (inclui Chrome + driver)
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    unzip \
    curl \
    gnupg2 \
    libglib2.0-0 \
    libnss3 \
    libfontconfig1 \
    libxss1 \
    fonts-liberation \
    libasound2 \
    xdg-utils \
    libu2f-udev \
    && rm -rf /var/lib/apt/lists/*

# Instalar Google Chrome estável
RUN wget -q -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt-get update \
    && apt-get install -y /tmp/google-chrome.deb \
    && rm /tmp/google-chrome.deb

# Variável para o Chrome
ENV CHROME_BIN=/usr/bin/google-chrome

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

# Comando para rodar o Flask com hot reload
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]